/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TypeWriterPackage;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author HP
 */
public class MultiFrame extends javax.swing.JFrame {

    /**
     * Creates new form MultiFrame
     */
    String user;
    private final String file;
    public MultiFrame(String user, String file) {
        this.user = user;
        this.file = file;
        initComponents();
        try {
            setParagraph();
        } catch (IOException ex) {
            Logger.getLogger(MultiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initialiser();
        writeTextField.requestFocusInWindow();
    }
    
    public void setParagraph() throws FileNotFoundException, IOException
    {
        String text = "";
        FileReader fileReader = new FileReader("C:\\Users\\HP\\Desktop\\"+file+".txt");
        BufferedReader br = new BufferedReader(fileReader);
        String s= "";
        while((s = br.readLine()) != null)
        {
            text = text+s;
            text = text + "\n";
        }
        br.close();
        fileReader.close();
        dataTextPane.setText(text);
        dataTextPane.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
    }
    
    private void initialiser() {
       SpeedChecker speedChecker = new SpeedChecker();
       Thread thread1 = new Thread(speedChecker);
       thread1.start();
       
       Checker3 checker = new Checker3(dataTextPane,writeTextField,speedChecker,user);
       Thread thread = new Thread(checker);
       thread.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rankingsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingsTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTextPane = new javax.swing.JTextPane();
        writeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rankingsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rankingsLabel.setText("Contest Rankings");

        rankingsTextPane.setEditable(false);
        jScrollPane1.setViewportView(rankingsTextPane);

        dataTextPane.setEditable(false);
        dataTextPane.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(dataTextPane);

        writeTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(writeTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rankingsLabel)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rankingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane dataTextPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rankingsLabel;
    private javax.swing.JTextPane rankingsTextPane;
    private javax.swing.JTextField writeTextField;
    // End of variables declaration//GEN-END:variables
}
