/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TypeWriterPackage;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author Harshit
 */
public class SinglePlayer extends javax.swing.JFrame {

    String user;
    String files[] = {"f1","f2","f3","f4"};
    String file;
    public SinglePlayer(String user) throws IOException {
        this.user = user;
        initComponents();
        setParagraph();
        initialiser();
        userTextField.requestFocusInWindow();
    }
    
    public void setParagraph() throws FileNotFoundException, IOException
    {
        Random rn = new Random();
        int j = (rn.nextInt()%4+4) % 4;
        file = files[j];
        String text = "";
        FileReader fileReader = new FileReader("C:\\Users\\HP\\Desktop\\"+file+".txt");
        BufferedReader br = new BufferedReader(fileReader);
        String s= "";
        while((s = br.readLine()) != null)
        {
            text = text+s;
            text = text + "\n";
        }
        br.close();
        fileReader.close();
        mainTextArea.setText(text);
        mainTextArea.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
    }
    
    private void initialiser() {
       SpeedChecker speedChecker = new SpeedChecker();
       Thread thread1 = new Thread(speedChecker);
       thread1.start();
       
       Checker2 checker = new Checker2(mainTextArea,userTextField,speedChecker,user);
       Thread thread = new Thread(checker);
       thread.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeWriterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextPane();
        userTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 404));

        mainTextArea.setEditable(false);
        mainTextArea.setBackground(new java.awt.Color(255, 204, 255));
        mainTextArea.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(mainTextArea);

        userTextField.setBackground(new java.awt.Color(255, 255, 102));
        userTextField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout typeWriterPanelLayout = new javax.swing.GroupLayout(typeWriterPanel);
        typeWriterPanel.setLayout(typeWriterPanelLayout);
        typeWriterPanelLayout.setHorizontalGroup(
            typeWriterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(userTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        typeWriterPanelLayout.setVerticalGroup(
            typeWriterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeWriterPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getContentPane().add(typeWriterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane mainTextArea;
    private javax.swing.JPanel typeWriterPanel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
